import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "CodeJoB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col`}>
        <div className="bg-[#f5f5f5] min-w-full overflow-hidden flex flex-col min-h-dvh">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
