import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        flex flex-col justify-center items-center min-h-dvh rounded-full bg-radial-[at_25%_25%] from-white to-zinc-900 to-75% pt-[5rem] pb-[10rem] pr-[10rem] pl-[10rem]
        `}
      >
        <div className="bg-[#f5f5f5] min-w-full rounded-md overflow-hidden">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
